### Rota GET para listar aluno OBS:(inserir o token de login no Authorization: Bearer )
GET http://localhost:3000/api/aluno/perfil
Content-Type: application/json
Authorization: Bearer 

### Rota Post para cadastrar aluno
POST http://localhost:3000/api/aluno/cadastrar
Content-Type: application/json

{
    "nome": "José",
    "notas": 70,
    "email": "jose@senac.com.br",
    "senha": "12345678"
}

### Rota PUT para atualizar informações OBS:(inserir o token de login no Authorization: Bearer )
PUT http://localhost:3000/api/aluno/perfil
Content-Type: application/json
Bearer

{
    "nome": "José Editado",
    "notas": 70,
    "email": "jose@senac.com.br",
    "senha": "12345678"
}

### Rota DELETE para atualizar informações
DELETE http://localhost:3000/api/aluno/perfil
Content-Type: application/json


### login aluno
POST http://localhost:3000/api/aluno/login
Content-Type: application/json
{
    "email": "jose@senac.com.br",
    "senha": "12345678"
}