### Rota GET para listar aluno 
GET http://localhost:3000/api/aluno/perfil
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb3NlQHNlbmFjLmNvbS5iciIsImlhdCI6MTczNzA2OTc2MiwiZXhwIjoxNzM3MTU2MTYyfQ.ZnhXwn7nj7xiMd8TYNU2IfgduZQ_Xd0LE3sl8EDhOuA



### Rota Post para cadastrar aluno
POST http://localhost:3000/api/aluno/cadastrar
Content-Type: application/json

{
    "nome": "José",
    "notas": 70,
    "email": "jose@senac.com.br",
    "senha": "12345678"
}

### Rota PUT para atualizar informações 
PUT http://localhost:3000/api/aluno/perfil
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb3NlQHNlbmFjLmNvbS5iciIsImlhdCI6MTczNzA2OTc2MiwiZXhwIjoxNzM3MTU2MTYyfQ.ZnhXwn7nj7xiMd8TYNU2IfgduZQ_Xd0LE3sl8EDhOuA


{
    "nome": "José Editado",
    "notas": 70,
    "email": "jose@senac.com.br",
    "senha": "12345678"
}

### Rota DELETE para atualizar informações
DELETE http://localhost:3000/api/aluno/perfil
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb3NlQHNlbmFjLmNvbS5iciIsImlhdCI6MTczNzA2OTc2MiwiZXhwIjoxNzM3MTU2MTYyfQ.ZnhXwn7nj7xiMd8TYNU2IfgduZQ_Xd0LE3sl8EDhOuA



### login aluno
POST http://localhost:3000/api/aluno/login
Content-Type: application/json

{
    "email": "jose@senac.com.br",
    "senha": "12345678"
}